-- ============================================
-- V8__offer_revision_and_lock.sql
-- PostgreSQL
-- ============================================

CREATE TABLE offer_revisions (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 offer_id BIGINT NOT NULL,
                                 revision_number INTEGER NOT NULL,

                                 customer_name VARCHAR(255) NOT NULL,
                                 customer_email VARCHAR(255) NOT NULL,
                                 description TEXT NOT NULL,

                                 total_price NUMERIC(10,2) NOT NULL,

                                 created_at TIMESTAMP NOT NULL,
                                 created_by BIGINT NOT NULL,

                                 CONSTRAINT fk_offer_revision_offer
                                     FOREIGN KEY (offer_id)
                                         REFERENCES offers(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT fk_offer_revision_user
                                     FOREIGN KEY (created_by)
                                         REFERENCES users(id)
);

-- indexy pro výkon
CREATE INDEX idx_offer_revisions_offer_id
    ON offer_revisions(offer_id);

CREATE INDEX idx_offer_revisions_revision_number
    ON offer_revisions(revision_number);
